name = "Porta"
uuid = "fb2f1d7b-1de9-45a3-b106-388808110f78"
authors = ["Mohammad Javad Azadi <mjazadi42@gmail.com>"]
version = "0.1.1"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"

[compat]
Makie = "0.9.5"
julia = "1.3"
